(cl:in-package object_msgs-msg)
(cl:export '(CAR2_T0-VAL
          CAR2_T0
          CAR3_T0-VAL
          CAR3_T0
          TRAJ_T0-VAL
          TRAJ_T0
          X0-VAL
          X0
          Y0-VAL
          Y0
          YAW0-VAL
          YAW0
          V0-VAL
          V0
          A0-VAL
          A0
          PLANNED_TRAJECTORIES-VAL
          PLANNED_TRAJECTORIES
          EGO_POLYGONS-VAL
          EGO_POLYGONS
          COSTS-VAL
          COSTS
          BEST_IND-VAL
          BEST_IND
          BEST_COST-VAL
          BEST_COST
          CAR2_PREDICTIONS-VAL
          CAR2_PREDICTIONS
          CAR3_PREDICTIONS-VAL
          CAR3_PREDICTIONS
          CAR2_POLYGONS-VAL
          CAR2_POLYGONS
          CAR3_POLYGONS-VAL
          CAR3_POLYGONS
))